// Tenant configuration — single source of truth for client-specific branding and features.
// In production this would come from auth/multitenancy. Here it's demo data for three sample tenants.

export const DEFAULT_TENANT_ID = "almanara";

export const TENANTS = {
  almanara: {
    id: "almanara",
    company: {
      name: "Al Manara Trading",
      legalName: "Al Manara Trading Co. W.L.L.",
      shortName: "Al Manara",
      logoUrl: null,
      locale: "ar-KW",
      fiscalYearStart: { month: 1, day: 1 },
      baseCurrency: "KWD",
      industry: "Trading",
    },
    banks: [
      {
        id: "kib",
        name: "Kuwait International Bank",
        shortName: "KIB",
        abbreviation: "KIB",
        brandColor: "#00C48C",
        logoUrl: null,
        embedded: true,
        accountNumberPrefix: "KWIB",
      },
    ],
    branding: {
      accentColor: "#00C48C",
      secondaryAccent: "#8B5CF6",
      logoText: "HASEEB.",
      logoMark: "H",
    },
    modules: {
      bankAccounts: true,
      bankTransactions: true,
      conversationalJE: true,
      rules: true,
      auditBridge: true,
      monthEndClose: true,
      financialStatements: true,
      team: true,
      budget: false,
      reconciliation: false,
      documents: false,
    },
    terminology: {
      ownerLabel: "Owner",
      cfoLabel: "CFO",
      juniorLabel: "Junior",
      seniorAccountantLabel: "Senior Accountant",
      apLabel: "Accounts Payable",
      periodName: "Period",
      closeName: "Month-End Close",
    },
    distributionMode: "bank-embedded",
    features: {
      showBankBranding: true,
      showFutureBankOperations: true,
      showAuditBridgeExternalAccess: true,
      enableArabicToggle: true,
      enableThemeToggle: true,
    },
  },

  boubyan_demo: {
    id: "boubyan_demo",
    company: {
      name: "Al Mawred Corporation",
      legalName: "Al Mawred Corporation W.L.L.",
      shortName: "Al Mawred",
      logoUrl: null,
      locale: "ar-KW",
      fiscalYearStart: { month: 1, day: 1 },
      baseCurrency: "KWD",
      industry: "Trading",
    },
    banks: [
      {
        id: "boubyan",
        name: "Boubyan Bank",
        shortName: "Boubyan",
        abbreviation: "BBY",
        brandColor: "#2D5F3F",
        logoUrl: null,
        embedded: true,
        accountNumberPrefix: "BBY",
      },
    ],
    branding: {
      accentColor: "#00C48C",
      secondaryAccent: "#8B5CF6",
      logoText: "HASEEB.",
      logoMark: "H",
    },
    modules: {
      bankAccounts: true,
      bankTransactions: true,
      conversationalJE: true,
      rules: true,
      auditBridge: true,
      monthEndClose: true,
      financialStatements: true,
      team: true,
      budget: false,
      reconciliation: false,
      documents: false,
    },
    terminology: {
      ownerLabel: "Owner",
      cfoLabel: "CFO",
      juniorLabel: "Junior",
      seniorAccountantLabel: "Senior Accountant",
      apLabel: "Accounts Payable",
      periodName: "Period",
      closeName: "Month-End Close",
    },
    distributionMode: "bank-embedded",
    features: {
      showBankBranding: true,
      showFutureBankOperations: true,
      showAuditBridgeExternalAccess: true,
      enableArabicToggle: true,
      enableThemeToggle: true,
    },
  },

  generic: {
    id: "generic",
    company: {
      name: "Demo Corporate",
      legalName: "Demo Corporate W.L.L.",
      shortName: "Demo Corporate",
      logoUrl: null,
      locale: "ar-KW",
      fiscalYearStart: { month: 1, day: 1 },
      baseCurrency: "KWD",
      industry: "Corporate",
    },
    banks: [
      {
        id: "generic",
        name: "Connected Bank",
        shortName: "BANK",
        abbreviation: "BNK",
        brandColor: null,
        logoUrl: null,
        embedded: false,
        accountNumberPrefix: "",
      },
    ],
    branding: {
      accentColor: "#00C48C",
      secondaryAccent: "#8B5CF6",
      logoText: "HASEEB.",
      logoMark: "H",
    },
    modules: {
      bankAccounts: true,
      bankTransactions: true,
      conversationalJE: true,
      rules: true,
      auditBridge: true,
      monthEndClose: true,
      financialStatements: true,
      team: true,
      budget: false,
      reconciliation: false,
      documents: false,
    },
    terminology: {
      ownerLabel: "Owner",
      cfoLabel: "CFO",
      juniorLabel: "Junior",
      seniorAccountantLabel: "Senior Accountant",
      apLabel: "Accounts Payable",
      periodName: "Period",
      closeName: "Month-End Close",
    },
    distributionMode: "standalone-direct",
    features: {
      showBankBranding: false,
      showFutureBankOperations: false,
      showAuditBridgeExternalAccess: true,
      enableArabicToggle: true,
      enableThemeToggle: true,
    },
  },
};

export const TENANT_IDS = Object.keys(TENANTS);
